### ISSUE TITLE
ImportError: cannot import name 'get_terminal_size'

### ISSUE THREAD

**Issue by pyvany** [fossasia/bbb-download#27]
hi everyone! I'm dealing with this problem.. what am I possibly doing wrong? I followed all the steps for "Usage per script".
![4](https://user-images.githubusercontent.com/102562604/160524441-66730269-d112-4382-a052-5a1d45b579ec.jpg)
Regards!

**Comment by mariobehling** [comment]
I am getting the same error: 

```
(venv) opntec@opntec:~/git/bbb-download$ python3.8 scripts/download_presentation.py https://video.eventyay.com 224ec3a3851dc806beee64734a4064fc15b3cff1-1649366854842
Traceback (most recent call last):
  File "scripts/download_presentation.py", line 6, in <module>
    import typer
  File "/home/opntec/git/bbb-download/venv/lib/python3.8/site-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/opntec/git/bbb-download/venv/lib/python3.8/site-packages/click/termui.py)
```
